### ISSUE TITLE
Can provide pre-trained models?

### ISSUE THREAD

**Issue by tearscoco** [tongxin-wang/TexFit#3]
Nice work! Shall we have the pre-trained models/weights for evaluation purposes also?

Thanks!

**Comment by tongxin-wang** [comment]
Of course! Thanks for your attention. We have released the pre-trained models. You can download them from [here](https://drive.google.com/drive/folders/1-bMjvtbY3X3TGoQXCjw3Bt9-Jv_lJomK?usp=sharing).
